### ISSUE TITLE
File missing?

### ISSUE THREAD

**Issue by xmangaz** [ansonb/Knowledge_Persistence#2]
https://github.com/ansonb/Knowledge_Persistence/blob/703417b85ab245a3786776c30a170cfe3fc8dd29/pykg2vec/make_preds_graphs_allepochs.py#L67

Hi,,

Is this file missing? I cannot find? 

Thanks :)

**Comment by xmangaz** [comment]
Hi again,,

How you create positive test graph, KP_test? If one sample order of $|E|$ triples and test dataset is smaller, should i also smple from train? 

(Sorry for my english, tell me please if need to clarify?)

**Comment by xmangaz** [comment]
Hi again,,

is there specific way you sample negative triple? i could not find in paper, so i just do randomly? thanks for a great paper :))

**Comment by ansonb** [comment]
Hi,

Thanks for your interest in our work and for reporting the issues.
I have uploaded the missing files.

Regarding your queries:
1) Sampling from train: We have experimented with both sampling from test set as well as train. So if your test set is small or not available you could sample from the train set to find the metric.
2) The sampling is random, though more advanced methods that maintain the topology could be experimented with and left to future works.

Let know if any further issues
Thanks
