### ISSUE TITLE
which distance to check correrlation with?

### ISSUE THREAD

**Issue by xmangaz** [ansonb/Knowledge_Persistence#3]
https://github.com/ansonb/Knowledge_Persistence/blob/703417b85ab245a3786776c30a170cfe3fc8dd29/compute_distance_bet_neg_graphs_extended.py#L216

Hi,,

With this output, two dists are given. which ones will be the correct measure correlation against ranking metrics?? Or is it weighted?

THanks :)

**Comment by ansonb** [comment]
Hello,

Thanks for your interest in our work.

With the two distances, I guess you are referring to the 0 and 1 dimensional PD distances. Empirically we have found the 0 dim PD (the first distance) to give better results. So you could try with using the first element of "dists".

Thanks
